/*
 * The words on every landing page, kept apart from the machinery that renders
 * them.
 *
 * Two rules govern everything in this file and neither is negotiable:
 *
 * 1. Every claim here is checkable against the code. No view counts, no
 *    customer numbers, no "10x faster" — nothing in this product records any
 *    of that, so writing it would be inventing it. Where a page says what
 *    DeenClipped does NOT do, that sentence is load-bearing: the editor is
 *    gated, there is no mobile app, no platform sends audience data back, and
 *    a visitor who finds that out after paying is a refund and a bad review.
 * 2. A page that describes a feature must be deleted or rewritten when that
 *    feature changes. test/seo-architecture.test.mjs asserts the shape; only
 *    reading holds the substance to account.
 *
 * Shape: { h1, lede, sections: [{heading, body}], faqs: [{q, a}], ctaLabel }.
 * marketing.seoPage() renders it; src/seo-pages.js decides which paths exist.
 */

export const SEO_COPY = {
  "/tools/ai-video-clipper": {
    h1: "AI video clipper that cuts on complete moments, not fixed intervals",
    lede: "Give it a YouTube link or an MP4, and mark the stretch worth clipping. You get back vertical clips with burned-in captions, each one waiting in a review queue for you to approve or reject.",
    sections: [
      { heading: "It cuts where the point ends",
        body: "Most of the quality in a clip comes down to where the cuts land. DeenClipped transcribes your selection with Whisper, word by word, then a self-hosted model reads that transcript, scores the candidate moments and says why it picked each one. The reasons are short and checkable: complete ending, question hook, stands alone. So a clip starts where the thought starts and ends where it lands, rather than at whatever second a fixed interval happened to fall on. The score and the reason travel with the clip, so you can judge the judgement." },
      { heading: "Nothing publishes until you say so",
        body: "Every clip lands in a review queue and stays there. You watch the rendered file itself — the exact video that would post, captions burned in and all — with its score and reasons beside it. Approve, reject, or send it back for another render. Keyboard shortcuts make that quick when a dozen are waiting. There is no setting that skips this step. Clips containing recited scripture are flagged and forced through human review even under automation, because an AI video clipper should never be the last check on a verse." },
      { heading: "Captions in the language that was actually spoken",
        body: "Word-level timings come out of the transcription, and captions are burned in with libass — word-by-word, karaoke, phrase or stacked lines, across five templates. Pin the language to English, Arabic or Urdu, or leave it on auto-detect, which switches per segment instead of guessing once from the opening seconds. An English talk containing Arabic recitation is handled as both. Recited Quran is matched against the 6,236-ayah corpus and rendered as the ayah with its translation, in Amiri. Other Arabic speech is captioned in Arabic with an English line beneath it." },
      { heading: "Framing, audio, and where approved clips go",
        body: "Face detection crops the 16:9 source to vertical 9:16 and keeps the speaker in frame. A nasheed is mixed underneath and ducked below the speech, and it can be switched off for a job. Once you approve, clips fill posting windows — four a day, eight on Studio — and publish to your connected YouTube, TikTok, Instagram and Facebook accounts. Each destination reports its own state, so one platform refusing a post does not mark the whole clip failed. You retry that leg on its own." },
      { heading: "You are charged for the minutes you choose",
        body: "One token is one source minute, and you choose the stretch. Set a start and end inside a ninety-minute lecture and only those minutes are downloaded and processed. The shortest selectable range is thirty seconds. Cutting more clips from the same lecture costs nothing further, and neither does re-rendering or editing one you already have — those source minutes were paid for once. A failed render is never charged, and neither is a clip you reject before export. Basic is free, with 40 tokens to try it on something real." },
    ],
    faqs: [
      { q: "How does an AI video clipper decide which parts to keep?",
        a: "This one reads the words, not the picture. Your selected stretch is transcribed with word-level timings, then a self-hosted model scores the candidate moments and returns a short reason for each: complete ending, question hook, stands alone. Cuts land on complete thoughts rather than on a timer. The score and reason go into the review queue with the clip, so the decision is yours and you can see what it was based on." },
      { q: "Does it post clips automatically?",
        a: "No. Every clip waits in a review queue for a human decision. You watch the rendered file, then approve, reject or send it back. Approved clips drop into posting windows and go out to the accounts you have connected. Clips containing scripture are pushed through review no matter what automation is switched on, and that gate cannot be turned off." },
      { q: "Do I have to process the whole video?",
        a: "No, and it would be a waste to. Paste a YouTube URL or upload an MP4 or MOV, then set a start and end time. Only that stretch is downloaded and processed, and only those minutes are charged, at one token per source minute. Thirty seconds is the shortest range. Picking three minutes out of a long lecture costs three minutes, not ninety." },
      { q: "Can it handle Arabic, or a talk that switches languages?",
        a: "Yes. Language can be pinned to English, Arabic or Urdu, or left on auto-detect, which switches per segment instead of deciding once from the opening seconds. Arabic speech that is not scripture is captioned in Arabic with an English line beneath it. Recited Quran is matched against a 6,236-ayah corpus and rendered as the ayah with its translation, set in Amiri." },
    ],
    ctaLabel: "Start Basic free",
  },

  "/tools/long-video-to-shorts": {
    h1: "Long video to shorts, starting with the stretch worth clipping",
    lede: "Paste a YouTube link or upload an MP4, set a start and end time on the part worth clipping, and only that stretch is processed. What comes back is vertical clips with burned-in captions, each waiting in a review queue for your decision.",
    sections: [
      { heading: "You pick the minutes, and only those minutes are fetched",
        body: "A ninety-minute lecture might hold eight minutes worth posting. Set a start and end time before the job runs, and only that stretch is downloaded from the source and processed. Nothing else is fetched, and nothing else is billed: one token is one source minute of what you selected, not of the file it came from. The shortest range you can pick is thirty seconds. If you are unsure where the good part sits, take a few minutes either side — cutting more clips from the same lecture later costs no extra tokens." },
      { heading: "Cuts land where a thought finishes",
        body: "Going from long video to shorts is a transcription problem before it is a video problem. The stretch is transcribed with a timing on every word, and a self-hosted model then reads that transcript and scores the moments inside it — cutting where a point finishes rather than every sixty seconds. Each candidate carries a short reason: complete ending, question hook, stands alone. Language can be pinned to English, Arabic or Urdu, or left on auto-detect, which switches per segment, so an English talk with recitation in the middle is read as two languages rather than mangled into one." },
      { heading: "Vertical, captioned, and framed on the speaker",
        body: "Each clip is cropped from 16:9 to 9:16 with face detection following the speaker, so the frame does not sit on an empty shoulder. Captions are burned into the picture with libass, timed to the words as spoken — word-by-word, karaoke, phrase or stacked lines, depending on the template. There are five templates: Bold Stack, Clean Line, Headline, Mono Minimal and Quran Recitation. A nasheed is mixed underneath and ducked whenever someone speaks; you can switch the music off for a job if you would rather have the room." },
      { heading: "Recitation is handled as recitation",
        body: "Recited Quran is matched against all 6,236 ayat and rendered as the verse with its translation, rather than as a phonetic guess from a transcriber. Arabic that is not scripture is captioned in Arabic with an English line beneath it, from a second translate pass. Arabic sets in Amiri. Any clip carrying scripture is flagged and forced into human review, and that gate does not lift for automation. The Quran Recitation template captions the verse and nothing else — a half-heard aside under an ayah is exactly what makes these clips look wrong." },
      { heading: "Nothing leaves until you approve it",
        body: "Every clip lands in a review queue and stays there. You watch the rendered clip itself — the same file that would post — with its score and the reasons beside it, then approve, reject or send it back. Keyboard shortcuts make a stack of them quick. Approved clips go into posting windows, four a day, eight on Studio, and publish to connected YouTube, TikTok, Instagram and Facebook accounts. Each destination reports its own state, so one platform refusing does not mark the whole clip failed. A failed render, or a clip you reject before export, is never charged." },
    ],
    faqs: [
      { q: "How do I turn a long video into shorts without processing the whole file?",
        a: "Import it by YouTube link, or upload an MP4 or MOV, then set a start and end time on the part you want. Only that stretch is downloaded and processed. A ninety-minute lecture where you select six minutes costs six tokens rather than ninety, and the job finishes sooner because there is less to transcribe. Thirty seconds is the shortest range you can select." },
      { q: "Does it work on a video with Arabic in it?",
        a: "Yes. Left on auto-detect, transcription switches language per segment, so an English talk containing Arabic recitation is read correctly in both rather than as one language throughout. Recited Quran is matched against the 6,236-ayah corpus and rendered as the ayah with its translation. Arabic speech that is not scripture is captioned in Arabic with an English line under it. Arabic sets in Amiri." },
      { q: "Can I try it before paying?",
        a: "Basic is free: 40 tokens across a seven-day trial, which is 40 source minutes. That is enough to pull several stretches out of a long video and see the clips rendered, captioned and sitting in the review queue. Pro and Studio are paid, billed weekly, monthly or yearly. Re-rendering a clip or cutting more clips from the same lecture costs no extra tokens." },
      { q: "Will it post to my channels automatically?",
        a: "Not without you. Every clip waits in the review queue for a human decision — the AI finds the moment, you decide what leaves. Once approved, a clip is scheduled into a posting window, four a day or eight on Studio, and published to connected YouTube, TikTok, Instagram and Facebook accounts. Clips containing scripture are always held for review, whatever your automation settings say." },
    ],
    ctaLabel: "Clip your first video",
  },

  "/tools/podcast-clip-generator": {
    h1: "Podcast clip generator for two-hour conversations",
    lede: "Give it an episode — a YouTube link or an MP4 — and the stretch worth clipping. You get back captioned vertical clips, cut on complete moments, each one waiting in a review queue for your decision.",
    sections: [
      { heading: "Two hours of talking, nine minutes worth posting",
        body: "DeenClipped transcribes the episode with Whisper, keeping word-level timings, then a self-hosted model reads that transcript and scores candidate moments. It cuts on complete moments rather than fixed intervals, so a clip starts where the thought starts and ends where it lands. Each candidate comes back with short reasons like 'complete ending', 'question hook' or 'stands alone', so you can see why it was picked before watching it. That last one carries the most weight in a long conversation. A good answer that depends on a question asked forty minutes earlier is not a clip." },
      { heading: "Captions burned in, timed to the word",
        body: "Most people watch a podcast clip with the sound off, so captions are burned into the video rather than shipped as a separate file. DeenClipped renders them with libass against the word-level timings from transcription, in four modes — word-by-word, karaoke, phrase and stacked lines — across five templates including Bold Stack, Clean Line and Mono Minimal. The frame is cropped from 16:9 to vertical 9:16 using face detection, so whoever is speaking stays in shot. A background nasheed is mixed under the speech and ducked when someone talks; it is on by default and can be switched off for a job." },
      { heading: "Nothing leaves until you approve it",
        body: "Every clip lands in a review queue and waits for a human decision. You watch the rendered clip itself — the same file that would post — with its score and the reasons it was picked. Approve, reject or send it back; keyboard shortcuts move you through a stack without reaching for the mouse. Approved clips go into posting windows, four a day or eight on Studio, and publish to your connected YouTube, TikTok, Instagram and Facebook accounts. Each destination reports its own state, so one platform refusing does not mark the whole clip failed." },
      { heading: "Episodes that switch language mid-sentence",
        body: "Pin the language to English, Arabic or Urdu, or leave it on auto-detect, which decides per segment instead of once from the opening minute. An English conversation containing Arabic is handled properly: the Arabic is captioned in Arabic, in the Amiri typeface, with an English line beneath it. Recited Quran is matched against a corpus of all 6,236 ayat and rendered as the verse with its translation. Any clip containing scripture is flagged and forced into human review, and that gate never bypasses, whatever else is automated." },
      { heading: "You pay for the stretch you point at",
        body: "Pick a start and an end time before anything is processed. Only that stretch is downloaded from the source, so a twelve-minute selection out of a two-hour episode costs twelve minutes of processing rather than two hours. One token is one source minute, and the minimum selectable range is thirty seconds. Re-rendering a clip, cutting more clips from an episode you have already processed, and editing cost nothing further. Failed renders are never charged, and neither is a clip you reject before it exports. Basic is free: forty tokens over a seven-day trial." },
    ],
    faqs: [
      { q: "Can I use a YouTube link, or do I have to upload the file?",
        a: "Both work. Paste a YouTube URL or upload an MP4 or MOV. Either way you choose a start and an end time first, and only that stretch is downloaded and processed — the rest of the episode is never fetched. The minimum selectable range is thirty seconds." },
      { q: "Does it add captions automatically?",
        a: "Yes, and they are burned into the video, not handed to you as a subtitle file to upload separately. Transcription produces word-level timings and libass renders against them, so the words land with the speech. You choose between word-by-word, karaoke, phrase and stacked-line modes, and one of five templates. Arabic renders in Amiri with an English line beneath it." },
      { q: "Will it post clips to TikTok and YouTube for me?",
        a: "Only after you approve them. Every clip waits in a review queue for a human decision — approve, reject or send back — and nothing publishes without one. Approved clips are scheduled into posting windows, four a day or eight on Studio, and go to your connected YouTube, TikTok, Instagram and Facebook accounts. DeenClipped does not report view counts or watch time; no connected platform sends that data back." },
      { q: "What does it cost to clip one episode?",
        a: "One token is one source minute, charged on the stretch you select rather than the length of the episode. Twenty minutes selected out of a two-hour recording costs twenty tokens. Re-rendering, cutting more clips from an episode you have already processed, and editing cost nothing more. Failed renders and clips rejected before export are never charged. Basic is free: forty tokens over a seven-day trial. Pro and Studio bill weekly, monthly or yearly." },
    ],
    ctaLabel: "Clip an episode free",
  },

  "/tools/lecture-clip-generator": {
    h1: "Lecture clip generator for talks where the words matter",
    lede: "Give it a YouTube link or an MP4, then mark the stretch worth clipping. You get back vertical clips cut on complete points, captions burned in and timed to the words, each one waiting in a review queue for your decision.",
    sections: [
      { heading: "You choose the minutes, and only those are processed",
        body: "A 90-minute seminar might hold six minutes worth clipping. Import from a YouTube URL or upload an MP4 or MOV, then set a start and an end time. Only that stretch is downloaded and processed, down to a minimum range of 30 seconds. Billing follows the same line. One token is one source minute, counted on the range you chose rather than the length of the recording, so eight minutes out of a two-hour talk costs eight tokens. Cutting more clips from a lecture already processed costs nothing further." },
      { heading: "Cuts land on complete points, not fixed intervals",
        body: "Whisper transcribes the selection with word-level timings, so the system knows where each sentence starts and stops. A self-hosted model then scores candidate moments and returns its reasoning in short phrases: complete ending, question hook, stands alone. Clips are cut on those complete moments rather than at fixed intervals. That is the whole job of a lecture clip generator, to find the point that survives being lifted out of an hour of context and leave the rest alone. Face detection crops the 16:9 frame to vertical 9:16 and keeps the speaker in it, and a nasheed sits beneath the speech, ducked so it never competes with the words." },
      { heading: "Captions for a talk that moves between Arabic and English",
        body: "Pin the language to English, Arabic or Urdu, or leave it on auto-detect. Auto-detect is multilingual and switches per segment, so an English talk containing Arabic recitation is handled rather than judged once from its opening minute and rendered as nonsense thereafter. Arabic speech that is not scripture is captioned in Arabic with an English line beneath it, taken from a second translate pass, and set in Amiri. Captions are burned into the video with libass, timed to the words. Word-by-word, karaoke, phrase and stacked-line modes run across five templates: Bold Stack, Clean Line, Headline, Mono Minimal and Quran Recitation." },
      { heading: "Recited Quran is matched, never guessed",
        body: "Recited Quran is matched against a corpus of all 6,236 ayat and rendered as the verse with its translation, rather than as whatever the transcriber thought it heard. The Quran Recitation template captions scripture and nothing else, so a half-heard aside never sits under a verse. Any clip containing scripture is flagged QUOTE_RISK and forced into human review. That gate does not bypass under any setting. Automation can shorten the path to a decision; it cannot make the decision on a clip carrying scripture." },
      { heading: "Nothing publishes until you say so",
        body: "Every clip lands in a review queue and waits. You watch the rendered clip itself, the same file that would post, with its score and the reasons it was picked beside it, then approve, reject or send it back. Keyboard shortcuts make a stack quick to work through. Approved clips drop into posting windows, four a day and eight on Studio, and go out to your connected YouTube, TikTok, Instagram and Facebook accounts. Each destination reports its own state, so one platform refusing a clip does not file the whole thing as failed." },
    ],
    faqs: [
      { q: "Can it clip a lecture that mixes English and Arabic?",
        a: "Yes. Leave the language on auto-detect and transcription runs multilingual, switching per segment instead of deciding once from the first minute. Arabic that is not scripture is captioned in Arabic with an English line beneath it, from a second translate pass. Recited Quran is matched against the full ayah corpus and rendered as the verse with its translation. Arabic sets in Amiri." },
      { q: "Do the clips post automatically once they are generated?",
        a: "No. Every clip lands in a review queue and waits for a human decision: approve, reject, or send it back. Approved clips are scheduled into posting windows and published to the YouTube, TikTok, Instagram and Facebook accounts you have connected. Clips containing scripture are additionally flagged and forced into review, and that gate never bypasses, whatever the automation settings say." },
      { q: "How much of the lecture am I charged for?",
        a: "Only the stretch you select. One token is one source minute, measured on the range you set, so eight minutes chosen out of a two-hour seminar costs eight tokens rather than a hundred and twenty. Re-rendering a clip and cutting more clips from the same lecture never cost extra. Failed renders and clips rejected before export are not charged. Basic is free: 40 tokens across a seven-day trial." },
      { q: "What can I import, and how short can a selection be?",
        a: "Import from a YouTube URL, or upload an MP4 or MOV. Set a start and end time, and only that stretch is downloaded and processed. The shortest selectable range is 30 seconds. Output is vertical 9:16, cropped from the 16:9 source with face detection keeping the speaker framed, with captions burned into the file rather than added as a separate track." },
    ],
    ctaLabel: "Start Basic free",
  },

  "/tools/ai-caption-generator": {
    h1: "An AI caption generator that burns captions into the clip",
    lede: "Paste a YouTube link or upload an MP4. You get back vertical clips with the captions rendered into the video itself, timed to each word as it was spoken.",
    sections: [
      { heading: "The words go into the picture, not into a sidecar file",
        body: "Ask most tools for subtitles and you get a transcript file back, with the job of putting it on the video still yours. DeenClipped renders the words into the picture itself with libass, on the same pass that cuts and frames the clip. What you approve in review is the exact file that posts — same words, same timing, same place in the frame. Clips come out vertical 9:16, cropped from a 16:9 source by face detection rather than a fixed centre crop." },
      { heading: "Word-level timing, and a language that can change mid-lecture",
        body: "Transcription is Whisper with word-level timings, so a word-by-word caption changes on the word rather than on a guess at where the line divides. Language can be pinned to English, Arabic or Urdu, or left on auto-detect. Auto-detect is multilingual and switches per segment, which is the case that usually breaks: a mostly-English talk that drops into thirty seconds of Arabic recitation. The whole file is not forced into one language because of how the first few seconds sounded." },
      { heading: "Four caption modes, five templates, no charge for changing your mind",
        body: "Four caption modes ship: word-by-word, karaoke, phrase and stacked lines. Five templates carry the rest of the look — Bold Stack, Clean Line, Headline, Mono Minimal and Quran Recitation. Trying them against each other is cheap, because the token charge is for the source minutes you selected and nothing after that. Re-rendering a clip in a different style, or cutting more clips from the same lecture, does not charge that source time again. A render that fails, or a clip you reject before export, is never charged." },
      { heading: "Arabic and recitation are not captioned like English",
        body: "Arabic is not English in a different alphabet, so it is not captioned that way. Spoken Arabic that is not scripture gets an Arabic caption with an English line beneath it, from a second translate pass, set in Amiri. Recited Quran is matched against a 6,236-ayah corpus and rendered as the ayah with its translation, not a phonetic guess. The Quran Recitation template captions scripture and nothing else. Anything containing scripture is flagged QUOTE_RISK and forced into human review, and that gate never bypasses. The Arabic and English captions page goes further into it." },
      { heading: "You read every line before anything leaves",
        body: "Nothing publishes on its own. Every clip lands in a review queue and waits for a person. You watch the rendered clip itself — not a browser preview drawing its own captions over a source file — with the score and the short reasons beside it, like \"complete ending\" or \"stands alone\". Approve, reject or send it back; there are keyboard shortcuts for working through a batch. Approved clips fill posting windows, four a day or eight on Studio, and go out to connected YouTube, TikTok, Instagram and Facebook accounts. Each destination reports its own result." },
    ],
    faqs: [
      { q: "Are the captions burned into the video or a separate subtitle file?",
        a: "Burned in. The words are rendered into the frame with libass as part of the clip, so there is no sidecar file to upload and no platform deciding whether to display it. Timing comes from Whisper's word-level output, so word-by-word and karaoke modes land on the word rather than drifting across the line. The clip you approve is the file that posts." },
      { q: "Can it caption Arabic and English in the same video?",
        a: "Yes. Leave the language on auto-detect and it switches per segment, so an English talk that drops into Arabic recitation is handled without the whole file being forced into one language. Non-scripture Arabic is captioned in Arabic with an English line beneath it, from a second translate pass, set in Amiri. Recited Quran is matched to a 6,236-ayah corpus and rendered as the ayah with its translation." },
      { q: "How much does the AI caption generator cost?",
        a: "One token is one source minute, and you are charged for the stretch you select rather than the whole video — pick three minutes of a ninety-minute lecture and you pay three. Basic is free: 40 tokens over a seven-day trial. Pro and Studio are paid, billed weekly, monthly or yearly. Re-rendering a clip in a different caption style costs nothing further, and a failed render is never charged." },
      { q: "Do I have to cut the clip first, or can I give it a full lecture?",
        a: "Give it the full thing. Paste a YouTube URL or upload an MP4 or MOV, then set a start and end time — thirty seconds is the shortest range you can select. Only that stretch is downloaded and processed. Inside it, moments are scored and cut where a point actually finishes rather than at fixed intervals, then framed vertically and captioned." },
    ],
    ctaLabel: "Caption a clip free",
  },

  "/tools/youtube-to-shorts": {
    h1: "YouTube to Shorts: paste a link, approve what publishes",
    lede: "Paste a YouTube URL and pick the minutes worth clipping. You get back vertical 9:16 clips with captions burned in, each one waiting in a review queue until you approve it for your own channel.",
    sections: [
      { heading: "Only the minutes you pick are downloaded",
        body: "Paste a YouTube URL, or upload an MP4 or MOV if you already have the file. Then set a start and an end time. Only that stretch is downloaded and processed, so a three-minute selection out of a ninety-minute lecture costs three minutes of work rather than ninety. The shortest range you can select is thirty seconds. Billing follows the same rule: one token is one source minute, and you are charged for the stretch you chose, not the length of the video you linked." },
      { heading: "It cuts where the thought finishes",
        body: "The audio is transcribed with Whisper, which returns timings for individual words rather than rough blocks. A self-hosted model then reads that transcript and scores candidate moments, cutting where a point actually completes. Each candidate arrives with a short reason attached — complete ending, question hook, stands alone — so you can see why it was picked before you watch it. Nothing is sliced at a fixed interval, which is what usually leaves a Short ending mid-sentence." },
      { heading: "Vertical framing, captions burned into the file",
        body: "Every clip is rendered vertical. Face detection tracks the speaker, so the 16:9 frame is cropped to 9:16 around them rather than straight down the middle. Captions are burned in with libass and timed to the words, in word-by-word, karaoke, phrase or stacked-line modes. Five templates ship: Bold Stack, Clean Line, Headline, Mono Minimal and Quran Recitation. A nasheed is mixed underneath and ducked when someone speaks; you can switch it off for a job." },
      { heading: "Arabic and recitation are not treated as English",
        body: "Auto-detect is multilingual and switches per segment, so an English talk containing recitation is not forced into a single language. Recited Quran is matched against the full 6,236-ayah corpus and rendered as the ayah with its translation, set in Amiri. Arabic speech that is not scripture is captioned in Arabic with an English line beneath it, from a second translate pass. The Quran Recitation template captions scripture and nothing else. Any clip containing scripture is flagged and forced into human review." },
      { heading: "It waits for you before anything reaches your channel",
        body: "Every clip lands in a review queue and stops there. You watch the rendered file itself, with its score and its reasons beside it, then approve, reject or send it back, by button or by keyboard. Approved clips fill posting windows — four a day, eight on Studio — and go to your own connected YouTube, TikTok, Instagram and Facebook accounts. Each destination reports its own state, so one platform refusing does not mark the whole clip failed." },
    ],
    faqs: [
      { q: "Can I publish the Shorts straight back to my YouTube channel?",
        a: "Yes. Connect your own YouTube account and approved clips post to it. TikTok, Instagram and Facebook can be connected as well, and each destination reports its own result — if one refuses, the others still go out and only that leg is retried. Nothing posts until you have approved the clip in the review queue." },
      { q: "Do I pay for the whole YouTube video or just the part I clip?",
        a: "Only the part you select. One token equals one source minute, and the charge follows the start and end times you set, not the length of the video you pasted. Re-rendering a clip, cutting more clips from the same lecture and editing cost nothing extra. Failed renders and clips rejected before export are never charged." },
      { q: "How does it handle Arabic or Quran recitation in the video?",
        a: "Auto-detect switches language per segment, so recitation inside an English talk is recognised rather than transcribed as nonsense. Recited verses are matched against a 6,236-ayah corpus and shown as the ayah with its translation in Amiri. Other Arabic speech gets an Arabic caption with an English line beneath it. Clips containing scripture are always forced into human review." },
      { q: "Is there a free way to try it first?",
        a: "Basic is free: 40 tokens over a seven-day trial, which is forty source minutes. That is enough to import a stretch of a lecture, generate clips, review them and publish the ones you approve. Pro and Studio are paid, billed weekly, monthly or yearly. Studio raises the posting windows from four a day to eight." },
    ],
    ctaLabel: "Paste your first link",
  },

  "/tools/youtube-to-tiktok": {
    h1: "YouTube to TikTok: vertical clips you approve before they post",
    lede: "Paste a YouTube link, mark the minutes worth clipping, and get back vertical 9:16 clips with the captions burned in. Every one waits in a review queue until you approve it; approved clips go to your connected TikTok account.",
    sections: [
      { heading: "Paste the link, then mark the minutes you want",
        body: "A YouTube to TikTok run starts with a link and a range. Give it the URL, or upload an MP4 or MOV if you already hold the file, then set a start and an end on the part worth clipping — thirty seconds is the shortest range you can select. Only that stretch is downloaded and processed, so three minutes chosen from a ninety-minute lecture is three minutes of work, not ninety. Tokens follow the same line: one token is one source minute, charged on the stretch you picked rather than on the video you picked it from." },
      { heading: "Whisper reads it before anything is cut",
        body: "Whisper transcribes the audio with word-level timings. You can pin the language to English, Arabic or Urdu, or leave it on auto-detect, which switches per segment — so an English talk carrying Arabic recitation is handled rather than mangled into nonsense. A self-hosted model then scores candidate moments and gives its reason in a few words: complete ending, question hook, stands alone. Cuts land on complete moments rather than fixed intervals, which is why a clip does not open mid-sentence or stop just before the point lands." },
      { heading: "Vertical framing, captions burned in",
        body: "Speaker framing uses face detection to crop the 16:9 source to a vertical 9:16 frame, so the person speaking stays in it. Captions are burned into the video with libass and timed to the words — word-by-word, karaoke, phrase, or stacked lines — across five templates: Bold Stack, Clean Line, Headline, Mono Minimal and Quran Recitation. A nasheed is mixed underneath and ducked when someone speaks, so it sits behind the voice rather than over it. Music runs by default and can be switched off for a job." },
      { heading: "Connecting TikTok, and who gets to see the post",
        body: "Nothing reaches TikTok on its own. Every render lands in a review queue, where you watch the finished clip, see its score and the reasons behind it, then approve, reject or send it back — there are keyboard shortcuts for working through a stack. Posting needs your own TikTok account connected, and you choose the privacy level for each post yourself; TikTok's rules require that choice to be made deliberately, with nothing preselected, so there is no default to inherit. Approved clips post or take a slot in your schedule: four posting windows a day, eight on Studio." },
      { heading: "Recitation is not captioned like ordinary speech",
        body: "Recited Quran is matched against a corpus of all 6,236 ayat and drawn as the ayah with its translation, in the Amiri typeface. Arabic that is not scripture is captioned in Arabic with an English line beneath it, taken from a second translate pass. The Quran Recitation template captions scripture and nothing else, because a half-heard aside under a verse is what makes those clips look wrong. Any clip containing scripture is flagged and forced into human review. That gate does not bypass, under automation or anything else." },
    ],
    faqs: [
      { q: "Can I post to TikTok directly from DeenClipped?",
        a: "Yes, once your own TikTok account is connected. Clips never go out by themselves: you approve one in the review queue, choose the privacy level for the post, and it either publishes or takes the next slot in your posting schedule. Basic and Pro accounts have four posting windows a day; Studio has eight." },
      { q: "Do I have to download the whole YouTube video first?",
        a: "No. You give the link and mark a start and an end, and only that stretch is downloaded and processed — the shortest range you can select is thirty seconds. The same rule sets the cost: one token is one source minute, counted on the stretch you selected, so four minutes out of a two-hour lecture is four tokens. Failed renders and clips you reject before export are not charged." },
      { q: "Who decides whether the TikTok post is public or private?",
        a: "You do, on each post. TikTok's content-sharing rules require the creator to choose a privacy level deliberately, with nothing preselected, so DeenClipped does not pick one for you and does not carry a default over from the last clip. It is asked at the point you approve the clip for posting, and it applies to that post alone." },
      { q: "What happens if TikTok refuses a clip but YouTube accepts it?",
        a: "Each destination carries its own state. If a clip is going to TikTok, YouTube and Instagram and one of them refuses, the clip is not marked failed — the row names the destination that refused and offers a retry for that leg only. The platforms that accepted it keep the post they already have, and nothing is uploaded to them a second time." },
    ],
    ctaLabel: "Clip a YouTube video",
  },

  "/tools/youtube-to-reels": {
    h1: "Turn a YouTube video into Instagram Reels",
    lede: "Paste a YouTube link and mark the stretch worth clipping. You get back vertical 9:16 clips with the captions burned in, each one waiting in a review queue for your decision before it reaches Instagram.",
    sections: [
      { heading: "Only the minutes you mark get processed",
        body: "Going from YouTube to Reels starts with a link, or an upload of an MP4 or MOV. Then you set a start and an end time. Only that stretch is downloaded and processed, so taking four minutes out of a ninety-minute talk costs four minutes of work rather than the whole file. The shortest range you can select is thirty seconds. Billing follows the same rule: one token is one source minute, and you pay for the stretch you marked, not the length of the video you linked." },
      { heading: "The cut lands where the point finishes",
        body: "A self-hosted model reads the transcript and scores moments inside the stretch you chose. Clips are cut on complete moments rather than fixed intervals, so one does not open halfway through a sentence or stop before the answer arrives. Each candidate comes back with short reasons written out, like complete ending, question hook or stands alone, so you can see why it was picked before you watch it. The transcript is Whisper's, with timings down to the word, which is what the captions are built from later." },
      { heading: "Face detection does the 16:9 to 9:16 crop",
        body: "A 16:9 recording dropped into a 9:16 frame either crops the speaker out or leaves them off to one side. Face detection finds the speaker and crops around them, so the frame follows the person talking rather than the centre of the original picture. Audio gets the same attention as the picture. A nasheed is mixed underneath and ducked when speech comes in, so it sits behind the voice rather than over it. Music is on by default and can be switched off for a job." },
      { heading: "Captions are burned in, for a feed with the sound off",
        body: "If the sound is off, a clip that carries its point only in the audio says nothing. So the words go into the picture. Captions are burned in with libass and timed to the words as spoken, straight from the transcript's word-level timings. Four modes are available, word-by-word, karaoke, phrase and stacked lines, across five templates: Bold Stack, Clean Line, Headline, Mono Minimal and Quran Recitation. Arabic that is not scripture is captioned in Arabic with an English line beneath it, rendered in Amiri." },
      { heading: "Nothing reaches your Instagram until you have watched it",
        body: "Every clip lands in a review queue and waits. You see the rendered clip itself, the same file that would post, with its score and the reasons beside it. Approve, reject or send it back, with keyboard shortcuts for a long run. Clips holding recited scripture are flagged and forced into that review, and automation never bypasses it. Approved clips fill posting windows, four a day and eight on Studio, then publish to the Instagram, YouTube, TikTok and Facebook accounts you connect. Each destination reports its own state." },
    ],
    faqs: [
      { q: "Do I have to process the whole YouTube video?",
        a: "No. You set a start and an end time, and only that stretch is downloaded and processed. Picking three minutes out of a long lecture costs three minutes, not the length of the file. The shortest range you can select is thirty seconds. Tokens follow the same rule: one token is one source minute of the stretch you marked." },
      { q: "Does DeenClipped post the Reels to Instagram for me?",
        a: "It can, once you have approved them. Connect your Instagram account, approve a clip in the review queue, and it goes into a posting window, four a day and eight on Studio. Nothing publishes without an approval first. If Instagram accepts a clip and another connected platform refuses it, only that destination is marked as failed, not the clip." },
      { q: "How does it handle a talk that moves between English and Arabic?",
        a: "Pin the language to English, Arabic or Urdu, or leave it on auto-detect. Auto-detect works per segment rather than deciding once at the start, so an English talk containing Arabic recitation is handled properly. Recited Quran is matched against a 6,236-ayah corpus and rendered as the ayah with its translation. Any clip containing scripture is forced into human review before it can publish." },
      { q: "What does a Reel cost to make?",
        a: "One token is one source minute of the stretch you selected. Basic is free and includes 40 tokens over a seven-day trial. Pro and Studio are paid, billed weekly, monthly or yearly. Re-rendering a clip costs nothing extra, and neither does cutting more clips from a lecture you have already processed. Failed renders and clips you reject before export are never charged." },
    ],
    ctaLabel: "Paste a YouTube link",
  },

  "/islamic-video-clipper": {
    h1: "An Islamic video clipper that knows what it is captioning",
    lede: "Give it a lecture — a YouTube link or an MP4 — and the minutes of it worth clipping. You get back vertical clips with burned-in captions, recited ayat matched to the Quran and set with their translation, and a review queue where nothing leaves until you say so.",
    sections: [
      { heading: "Recited ayat are matched, not just transcribed",
        body: "The hard part of an Islamic video clipper is not the clipping. Whisper hears sound, and for recitation that is not enough — a phonetic transcript of an ayah is not the ayah. Recited Quran is matched against a corpus of all 6,236 ayat, and the clip carries the verse itself, set in the Amiri typeface, with its translation on the line beneath. Captions are burned in with libass and timed to the words as spoken, so the text keeps pace with the reciter. The Quran Recitation template goes further and captions scripture and nothing else, so no half-heard aside sits under a verse." },
      { heading: "An English talk with Arabic inside it is two languages",
        body: "Most transcription picks one language from the opening seconds and applies it to the whole file. An English lecture with two minutes of recitation in the middle comes back as Latin nonsense, and after that nothing can tell it was ever Arabic. Auto-detect here is multilingual and switches per segment. Arabic speech that is not scripture is captioned in Arabic with an English line beneath it, taken from a second translate pass. You can also pin the language — English, Arabic or Urdu — when you already know what is on the recording." },
      { heading: "Scripture cannot leave without a person seeing it",
        body: "Every clip lands in a review queue and waits for a human decision. Nothing publishes on its own. Clips containing scripture carry an extra flag, QUOTE_RISK, that forces review and never bypasses — not even under automatic approval. The reviewer watches the rendered clip, the same file that would post, with its score and the model's short reasons beside it: complete ending, question hook, stands alone. Approve, reject or send it back, with keyboard shortcuts for a long queue. The full clip editor is still behind a coming-soon notice and is not part of what you get today." },
      { heading: "What happens between the link and the first clip",
        body: "Give it a YouTube URL or an MP4, then pick the start and end of the stretch worth clipping — thirty seconds minimum. Only that stretch is downloaded and processed, so a three-minute selection from a ninety-minute lecture costs three minutes. Whisper transcribes it with word-level timings. A self-hosted Ollama model scores candidate moments and returns its reasons, and cuts land on complete moments rather than fixed intervals. Face detection crops 16:9 to vertical 9:16, a nasheed is mixed under the speech and ducked beneath it, and captions burn in word-by-word, karaoke, phrase or stacked, across five templates." },
      { heading: "Approved clips go out on your own channels",
        body: "An approved clip is scheduled into posting windows — four a day, eight on Studio — and published to the YouTube, TikTok, Instagram and Facebook accounts you have connected. Each destination reports its own state, so a clip that went live on YouTube is not filed as a failure because TikTok refused it. What you will not find here are view counts or watch time: no connected platform sends that data back, and there is no dashboard here inventing it." },
    ],
    faqs: [
      { q: "How much of my lecture am I charged for?",
        a: "One token is one source minute, and you are charged for the stretch you selected, not the length of the video it came from. Basic is free — forty tokens over a seven-day trial. Re-rendering a clip and cutting more clips from the same lecture never cost tokens again. A render that fails is not charged, and neither is a clip you reject before it exports." },
      { q: "What happens to a clip that contains a Quran verse?",
        a: "The recitation is matched against the 6,236-ayah corpus and rendered as the verse in Amiri with its translation beneath. The clip is then flagged as carrying scripture and forced into human review, which no automation setting can switch off. If you use the Quran Recitation template, scripture is the only thing captioned — the surrounding lecture is left off the screen." },
      { q: "Can I turn the background nasheed off?",
        a: "Yes, but you have to say so. A nasheed is mixed in by default and ducked under the speech, so the words stay clear; music is on unless it is explicitly switched off for that job. The rest of the look is set by the template you choose — Bold Stack, Clean Line, Headline, Mono Minimal or Quran Recitation — and the caption mode you pick with it." },
      { q: "Why not just use a general AI clipper?",
        a: "Three things. Recited Quran is matched against a 6,236-ayah corpus and set as the verse with its translation, rather than transcribed phonetically. Arabic speech that is not scripture is captioned in Arabic with an English line under it. And any clip containing scripture is forced into human review, whatever the automation settings say. The clipping itself — transcription, scoring, framing, captions — is the ordinary part." },
    ],
    ctaLabel: "Clip a lecture free",
  },

  "/islamic-lecture-clipper": {
    h1: "An Islamic lecture clipper that never cuts a point in half",
    lede: "Give it a YouTube link or an MP4 and the minutes of the talk worth clipping. You get back vertical clips with burned-in captions, each cut on a complete moment, waiting in a review queue for your decision.",
    sections: [
      { heading: "Why a khutbah breaks when you cut it by the clock",
        body: "Most clippers slice on a timer: sixty seconds, then the next sixty. A reminder does not work that way. The condition arrives before the ruling and the exception after it, so a cut in the wrong place leaves a half-sentence saying something the speaker never said. DeenClipped transcribes the talk with Whisper at word level, then a self-hosted model scores candidate moments and gives its reason — complete ending, question hook, stands alone. Clips are cut on those moments. Nothing is cut to fill an interval." },
      { heading: "Recitation is matched to the ayah, not guessed at by ear",
        body: "When a shaykh recites mid-talk, a phonetic transcript of the Arabic is not a caption — it is a mistake burned into the frame. Recited Quran is matched against a corpus of all 6,236 ayat and drawn as the verse itself with its translation beneath, set in Amiri. The Quran Recitation template goes further and captions scripture and nothing else, so a half-heard aside never sits under a verse. Arabic that is not scripture is captioned in Arabic with an English line under it, from a second translate pass." },
      { heading: "Nothing leaves until you have watched it",
        body: "An Islamic lecture clipper carries a risk a general one does not: a verse misquoted, or a ruling published without its condition. So every clip waits in a review queue. You watch the rendered file — the same bytes that would post — with its score and the model's reasons beside it, then approve, reject or send it back; keyboard shortcuts move you through a stack. Clips containing scripture are flagged QUOTE_RISK and forced into human review. That gate never bypasses, even under automation." },
      { heading: "You are charged for six minutes, not forty",
        body: "A khutbah runs forty minutes and the part worth clipping is often six. Pick a start and an end time and only that stretch is downloaded and processed — one token per source minute, charged on what you selected rather than the file's length. Thirty seconds is the minimum range. Cutting more clips from the same lecture costs nothing further, and neither does re-rendering one or changing its template. Failed renders, and clips you reject before export, are never charged. Basic is free: forty tokens over a seven-day trial." },
      { heading: "What happens to a clip after you approve it",
        body: "Face detection crops the 16:9 source to vertical 9:16 and keeps the speaker in frame. Captions burn in with libass, timed to the words — word-by-word, karaoke, phrase or stacked lines, across five templates. A nasheed is mixed under the speech and ducked, unless you switch it off for the job. Approved clips take posting windows, four a day and eight on Studio, and go to your connected YouTube, TikTok, Instagram and Facebook accounts. Each destination reports its own state, so one platform refusing does not mark the clip failed. There are no view counts here — no connected platform sends them." },
    ],
    faqs: [
      { q: "Can it handle a lecture that switches between English and Arabic?",
        a: "Yes. With no language pinned, transcription runs multilingual and switches per segment, so an English talk containing Arabic recitation is handled instead of having one language forced across the whole file. Spoken Arabic is captioned in Arabic with an English line beneath it, from a second translate pass. You can pin English, Arabic or Urdu instead if you already know what is on the recording." },
      { q: "What happens when the speaker recites Quran?",
        a: "The recitation is matched against the full corpus of 6,236 ayat and rendered as the ayah with its translation, set in Amiri, rather than as a phonetic guess at the Arabic. The clip is then flagged QUOTE_RISK and forced into human review, so you read the verse on the finished frame before it can go anywhere. The Quran Recitation template captions the scripture and nothing else." },
      { q: "How much of the lecture am I charged for?",
        a: "Only the stretch you select. Paste a YouTube URL or upload an MP4 or MOV, choose a start and end time, and just those minutes are downloaded, processed and billed, at one token per source minute. Thirty seconds is the minimum. Cutting more clips from the same lecture later costs nothing extra, and clips you reject before export, like failed renders, are never charged. Basic is free: forty tokens over a seven-day trial." },
      { q: "Does it post the clips automatically?",
        a: "No. Nothing publishes without a human approval — that is the point of the review queue. Once you approve a clip it takes a posting window, four a day and eight on Studio, and goes to your connected YouTube, TikTok, Instagram or Facebook account. Clips containing scripture carry a further gate that automation cannot skip, whatever else is switched on." },
    ],
    ctaLabel: "Clip your first lecture",
  },

  "/for/islamic-creators": {
    h1: "Muslim creator tools for the week you spend clipping lectures",
    lede: "Give it a lecture — a YouTube link or an MP4 — and the minutes worth clipping. You get back vertical clips, captioned and rendered, waiting in a queue for you to approve, reject or send back.",
    sections: [
      { heading: "The part of the week you would hand over",
        body: "A two-hour lecture lands, and the work is not deciding what matters — it is scrubbing to find it, cutting, subtitling, exporting, uploading four times. Paste a YouTube link or upload an MP4, set a start and an end, and only that stretch is downloaded and processed. Whisper transcribes it with word-level timings; a self-hosted model scores the moments inside and says why — complete ending, question hook, stands alone. Clips are cut on complete moments, not fixed intervals. Face detection crops 16:9 to vertical, and a nasheed sits under the speech, ducked while the speaker talks, or off for that job." },
      { heading: "Arabic is not an afterthought in the captions",
        body: "Most lectures move between languages without warning. Pin it to English, Arabic or Urdu, or leave auto-detect on: it is multilingual and switches per segment, so an English talk containing recitation is handled rather than flattened into one language. Spoken Arabic that is not scripture is captioned in Arabic with an English line beneath it, from a second translation pass, and renders in Amiri. Captions are burned into the video with libass, timed to the words — word-by-word, karaoke, phrase or stacked lines, across five templates: Bold Stack, Clean Line, Headline, Mono Minimal and Quran Recitation." },
      { heading: "Recitation is treated as scripture, not as text",
        body: "When someone recites, the transcript is not the answer. Recited Quran is matched against a 6,236-ayah corpus and rendered as the ayah itself with its translation, rather than whatever the transcriber heard. The Quran Recitation template captions scripture and nothing else — an aside or a half-heard word sitting under a verse is what makes those clips look wrong. And any clip containing scripture is flagged and forced into human review. That gate does not bend: not for automation, not for a schedule that is running behind." },
      { heading: "Nothing leaves the queue without you",
        body: "Every clip lands in a review queue and waits for a person. You watch the rendered clip itself — the same file that would post — with its score and the reasons underneath. Approve, reject or send it back; keyboard shortcuts are there for the ones you decide in a second. Approved clips go into posting windows, four a day, eight on Studio, and publish to the YouTube, TikTok, Instagram and Facebook accounts you have connected. Each destination reports its own state, so one platform refusing does not mark the clip failed or hide that the others went out." },
      { heading: "A token is a source minute, and that is the whole rule",
        body: "You are charged for the stretch you select, not the whole upload. Basic is free: 40 tokens over a seven-day trial. Cutting more clips from a lecture you have already processed costs nothing more. Neither does re-rendering one. A render that fails is not charged, and neither is a clip you reject before it exports — you pay for source minutes, not for changing your mind. That is enough to judge it against the other Muslim creator tools you are weighing up, on your own lectures rather than on a demo." },
    ],
    faqs: [
      { q: "Can it handle a lecture that switches between English and Arabic?",
        a: "Yes. Leave the language on auto-detect and it works per segment rather than picking one language from the opening seconds — so an English talk that breaks into recitation is handled. Arabic that is not scripture is captioned in Arabic with an English line beneath it, from a second translation pass, and renders in Amiri. You can also pin the language to English, Arabic or Urdu." },
      { q: "What happens if a clip contains Quran recitation?",
        a: "It is matched against a 6,236-ayah corpus and rendered as the ayah with its translation, rather than a transcript of what was heard. The Quran Recitation template captions scripture and nothing else. Any clip carrying scripture is flagged and forced into human review, so it cannot be approved or scheduled without a person watching it first. That gate has no override." },
      { q: "Does anything post without me approving it?",
        a: "No. Every clip waits in a review queue for a human decision — you watch the rendered file, see its score and the reasons, then approve, reject or send it back. Approved clips go into posting windows, four a day, eight on Studio, and publish only to accounts you have connected: YouTube, TikTok, Instagram and Facebook. If one destination refuses, the others still go out." },
      { q: "Do I still need other Muslim creator tools alongside this?",
        a: "Probably, for some things. There are no view counts or watch-time figures here — no connected platform sends them, so we do not show numbers we cannot stand behind. The full clip editor is still behind a coming-soon notice, so trimming and reframing by hand happens elsewhere for now. There is no mobile app. What is here is the run from a long lecture to reviewed, captioned, published clips." },
    ],
    ctaLabel: "Start Basic free",
  },

  "/tools/arabic-english-captions": {
    h1: "Arabic and English captions, burned into the same clip",
    lede: "You give it a lecture that moves between Arabic and English. You get back vertical clips where the Arabic is captioned in Arabic, with an English line under it, drawn from a second translation pass over the same audio.",
    sections: [
      { heading: "Why one language pass gets a mixed lecture wrong",
        body: "Most transcription detects one language from the opening seconds and applies it to the whole file. An English talk that breaks into a passage of recitation gets that Arabic written out as Latin nonsense, and once that has happened nothing downstream can tell it was ever Arabic. No Arabic typeface. No ayah match. No translation line. DeenClipped's auto-detect is multilingual and switches per segment, so the language can change in the middle of a lecture and the captions change with it. If a talk really is one language, pin it: English, Arabic or Urdu." },
      { heading: "The English line comes from a second pass over the same audio",
        body: "The first pass stays a transcription, because the Arabic words are what goes on screen and what the Quran matcher searches with; translating them away would cost both. So the audio is read a second time as a translate pass, and each English line is laid under the speech it covers, matched by time, because the two passes break the audio into different segments. It only runs when Arabic was actually transcribed. What lands on screen is the Arabic phrase with its English directly beneath it, the two moving together as one caption." },
      { heading: "Amiri for the Arabic, burned in with libass",
        body: "Arabic and English captions are burned into the video with libass, timed to the words from the transcript's word-level timings. Nothing ships as a separate subtitle file a platform can ignore or restyle. Arabic is set in Amiri, a revival of the naskh used in printed mushafs, rather than whatever the renderer would otherwise fall back to. Caption mode is per template: word-by-word, karaoke, phrase or stacked lines, across Bold Stack, Clean Line, Headline, Mono Minimal and Quran Recitation. The English sits directly under the Arabic phrase it translates, so it cannot drift onto the wrong line." },
      { heading: "Recited scripture is not treated as speech",
        body: "Recited Quran and ordinary Arabic speech are different problems. Recitation is matched against a 6,236-ayah corpus and drawn as the ayah itself with its translation, never as a transcription of it. The speaker's own Arabic, an aside or an explanation, gets the Arabic line with English beneath instead. The Quran Recitation template goes further: it captions scripture and nothing else, because a half-heard aside in the lecture face under a verse is what made those clips look wrong. Any clip containing scripture is flagged QUOTE_RISK and forced into human review. That never bypasses." },
      { heading: "You watch the clip before it goes anywhere",
        body: "Every clip lands in a review queue and waits for a person. You watch the rendered clip, the exact file that would post with the captions burned in, alongside its score and the model's reasons: complete ending, question hook, stands alone. Approve, reject or send it back, with keyboard shortcuts for the decisions you make most. Approved clips go into posting windows, four a day and eight on Studio, then out to your connected YouTube, TikTok, Instagram and Facebook accounts. Each destination reports its own state, so one platform refusing does not mark the clip failed." },
    ],
    faqs: [
      { q: "Can I pin the language instead of using auto-detect?",
        a: "Yes. Set the job to English, Arabic or Urdu and that is what the transcription is told, exactly as before. Auto-detect exists for the mixed case: a lecture in English that breaks into Arabic, or the other way round. Pinning is the better answer when a talk really is one language throughout, because there is nothing for per-segment detection to get wrong." },
      { q: "Do English-only clips get a translation line too?",
        a: "No. English captions as it always did, one line, in the caption mode your template uses. The second pass only fires when Arabic was actually transcribed, and the English line is only drawn under Arabic that is not scripture. A clip with no Arabic in it renders exactly as it would have without any of this." },
      { q: "What happens if the speaker recites Quran mid-sentence?",
        a: "That stretch is matched against the 6,236-ayah corpus and rendered as the ayah with its translation, rather than as a transcription of it. The Arabic from the transcript is used as the search query, never as the caption on screen. The clip is then flagged QUOTE_RISK, which forces it into human review; it cannot be auto-approved, whatever your automation settings say." },
      { q: "What does captioning a lecture cost?",
        a: "One token is one source minute, and you are charged for the stretch you select, not the whole video. The minimum selectable range is 30 seconds. Basic is free: 40 tokens across a 7-day trial. Re-rendering a clip and cutting more clips from the same lecture never cost extra tokens, and a failed render is never charged." },
    ],
    ctaLabel: "Start Basic free",
  },

  "/how-it-works": {
    h1: "How DeenClipped works, from lecture to published clip",
    lede: "You give it a lecture and the minutes you want out of it; you get back vertical clips with captions burnt in, each one waiting for your decision. This is how DeenClipped works, in the order it actually happens.",
    sections: [
      { heading: "You pick the source, and the exact minutes",
        body: "Paste a YouTube link or upload an MP4 or MOV. Then set a start and an end time; the shortest range you can select is 30 seconds. Only that stretch is downloaded and processed, so taking three minutes out of a ninety-minute lecture costs three minutes of work rather than ninety. Billing follows the same line. One token is one source minute, and you are charged for the range you picked, not for the length of the video you picked it from." },
      { heading: "Transcription first, then a search for complete moments",
        body: "Whisper transcribes the selected audio with word-level timings. You can pin the language to English, Arabic or Urdu, or leave it on auto-detect, which is multilingual and switches per segment, so an English talk containing Arabic recitation is handled rather than flattened into one language. A self-hosted Ollama model then reads the transcript and scores candidate moments, returning short reasons: complete ending, question hook, stands alone. Clips are cut on those complete moments, not at fixed intervals, so a point finishes before the clip does." },
      { heading: "Framing, burnt-in captions and a nasheed underneath",
        body: "Face detection crops the 16:9 source to vertical 9:16 and keeps the speaker in frame. Captions are burnt into the video with libass, timed to the words: word-by-word, karaoke, phrase or stacked lines, depending on the template. There are five templates, being Bold Stack, Clean Line, Headline, Mono Minimal and Quran Recitation. A nasheed is mixed in and ducked under the speech; music is on unless it is explicitly switched off for that job. What comes out is a finished vertical file, not a preview of one." },
      { heading: "When the words are Arabic, or scripture",
        body: "Recited Quran is matched against a 6,236-ayah corpus and rendered as the ayah with its translation, set in Amiri. Arabic speech that is not scripture is captioned in Arabic with an English line beneath it, taken from a second translate pass. The Quran Recitation template captions scripture and nothing else, so a half-heard aside never sits under a verse in the lecture face. Any clip containing scripture is flagged QUOTE_RISK and forced into human review. That gate never bypasses, whatever else is set to run on its own." },
      { heading: "Nothing leaves until you approve it",
        body: "Every clip lands in a review queue and waits there. You watch the rendered clip itself, the same file that would post, with its score and the reasons the model gave for choosing that moment. Approve it, reject it, or send it back; there are keyboard shortcuts for working through a stack. Approved clips fill posting windows, four a day and eight on Studio, and go to the YouTube, TikTok, Instagram and Facebook accounts you connected. Each destination reports its own state, so one platform refusing does not mark the clip failed." },
    ],
    faqs: [
      { q: "Does DeenClipped publish clips automatically?",
        a: "No. Every clip generated lands in a review queue and stays there until a person decides on it. There is no setting that skips that step. Clips containing scripture are additionally flagged QUOTE_RISK and forced through the same review, which is the one gate that never bypasses. Publishing only reaches accounts you connected yourself, and only after approval." },
      { q: "What does one DeenClipped token cover?",
        a: "One token is one source minute, counted against the stretch you selected rather than the length of the original video. Basic is free: 40 tokens across a seven-day trial. Pro and Studio are paid, billed weekly, monthly or yearly. Re-rendering a clip, cutting more clips from the same lecture and editing all cost nothing extra, and a failed render or a clip you reject before export is never charged." },
      { q: "How does DeenClipped handle Quran recitation?",
        a: "Recited Quran is matched against a 6,236-ayah corpus and rendered as the ayah with its translation, set in Amiri rather than the lecture caption face. The Quran Recitation template captions scripture and nothing else, so a half-heard aside never appears under a verse. Any clip containing scripture carries a QUOTE_RISK flag that forces a human decision before it can go anywhere." },
      { q: "What can DeenClipped not do yet?",
        a: "The full clip editor is built but sits behind a coming-soon notice, so choosing a template and re-rendering is how you change a clip's look today. There are no view counts, watch time or audience figures anywhere in the app, because no connected platform sends them. Posting to two accounts on the same platform is not built yet either. There is no mobile app." },
    ],
    ctaLabel: "Start Basic free",
  },

  "/review-safety": {
    h1: "AI video review safety: nothing publishes until a human approves it",
    lede: "DeenClipped finds the moments in your lecture and renders them. You watch each clip, then approve, reject or send it back. Nothing reaches a channel on its own.",
    sections: [
      { heading: "Every clip stops in the review queue",
        body: "The pipeline ends at a queue, not at a platform. A rendered clip waits there until a person decides. You see the actual finished video — the same file that would post, with its burned-in captions and mixed audio — plus the score the model gave it and the short reasons behind that score, like \"complete ending\" or \"question hook\". Approve, reject or send it back. Keyboard shortcuts are there if you review in volume. There is no setting that empties the queue for you, and no path that skips it." },
      { heading: "Scripture is forced into review and cannot bypass it",
        body: "Recited Quran is matched against a 6,236-ayah corpus and rendered as the ayah with its translation. Any clip containing scripture is flagged QUOTE_RISK, and that flag forces human review. It holds even when automation is switched on and the score is high. This is the one rule in the system with no override, because a misattributed or mistimed verse is not the same kind of mistake as a badly cut clip. If a clip carries scripture, you look at it before anyone else does." },
      { heading: "It can only post where you have connected an account",
        body: "Publishing goes to YouTube, TikTok, Instagram and Facebook accounts you have connected yourself. There is no other exit. Approved clips are scheduled into posting windows — four a day, eight on Studio — so you know when things go out. Each destination reports its own state independently. If TikTok refuses a clip that YouTube accepted, the clip is not marked failed and the working post is not undone; you retry the one leg that failed." },
      { heading: "The model suggests, it does not decide",
        body: "A self-hosted Ollama model scores candidate moments and explains why in a few words. Whisper supplies word-level timings, so clips are cut on complete thoughts rather than at fixed intervals. That is the extent of the model's authority. It ranks and it reasons out loud; it never approves, never schedules and never posts. The reasons exist so you can disagree with them quickly. Transcription and scoring run on infrastructure we host, so your lecture audio is not handed to a third-party model provider." },
      { heading: "Rejecting a clip costs you nothing",
        body: "A token is one source minute, charged on the stretch you selected, not the whole video. Clips you reject before export are never charged. Failed renders are never charged. Re-rendering, cutting more clips from the same lecture and editing a clip do not spend tokens again. The point is that saying no should be free, or review quietly turns into a cost you avoid. Basic gives you 40 tokens over a 7-day trial, which is enough to run a real lecture through and reject most of it." },
    ],
    faqs: [
      { q: "Can DeenClipped post clips automatically without me seeing them?",
        a: "No. Every clip lands in the review queue and waits for a human decision. Approval is what makes a clip eligible for scheduling, and scheduling is what makes it eligible to post. There is no auto-publish setting that removes the review step, and clips flagged QUOTE_RISK for containing scripture cannot bypass review under any configuration." },
      { q: "What does QUOTE_RISK mean and why does it force review?",
        a: "QUOTE_RISK is the flag set on any clip whose transcript contains recited scripture. It forces that clip into human review regardless of its score or your automation settings. Quran recitation is matched against a 6,236-ayah corpus and rendered as the ayah with its translation, and a verse rendered wrongly is a different order of mistake from a badly timed cut. A person checks it." },
      { q: "Where can my approved clips actually be published?",
        a: "Only to YouTube, TikTok, Instagram and Facebook accounts you have connected yourself. The app has no other publishing route. Approved clips go into posting windows — four a day, eight a day on Studio. Each destination reports its own outcome, so one platform refusing a clip does not mark the clip failed or undo the destinations that accepted it." },
      { q: "How much of my video and audio leaves my control?",
        a: "You choose a start and end time, and only that stretch is downloaded and processed — the rest of the video is never fetched. Transcription runs on Whisper and moment-scoring runs on a self-hosted Ollama model, both on infrastructure we run, so lecture content is not sent to an outside model provider. Publishing happens only to accounts you have connected." },
    ],
    ctaLabel: "Start free with 40 tokens",
  },

  "/about": {
    h1: "About DeenClipped, and why nothing posts without you",
    lede: "DeenClipped turns long Islamic lectures into short vertical clips with captions burned in. You give it a YouTube link or an MP4 and the stretch worth using; it gives you finished clips waiting in a review queue, where nothing leaves until you approve it.",
    sections: [
      { heading: "What DeenClipped actually does",
        body: "You import a lecture from a YouTube URL or upload an MP4, then pick the start and end of the stretch worth clipping. Only that stretch is downloaded and processed. Whisper transcribes it with word-level timings. A self-hosted model reads the transcript and scores candidate moments, returning short reasons such as complete ending, question hook or stands alone, so clips land on finished thoughts rather than fixed intervals. Each one is cropped from 16:9 to vertical using face detection, given a nasheed ducked under the speech, and captioned with the words burned into the picture." },
      { heading: "Who it is for, and who it is not",
        body: "It is built for people who publish Islamic talks: khutbahs, reminders, halaqas, tafsir series and recitation. If you already have hours recorded and no time to sit through them hunting for the parts that stand alone, that is the problem this solves. It assumes you care what goes out under your name, so it is a poor fit for anyone who wants a queue filled and never looked at. Clips reach the review queue, not your channel, and a clip carrying scripture waits for you whatever else is switched on." },
      { heading: "Why every clip waits for a human",
        body: "AI finds the moment; the creator decides what leaves. That split is the whole design. A model scoring a transcript will sometimes cut a sentence a word early, misjudge where an argument finishes, or pull a line that reads differently without the point that followed it. On ordinary content that is an awkward clip. On a verse or a hadith it is something worse. So every clip lands in a review queue and waits there. You see the rendered clip itself, its score and the reasons it was chosen, then approve, reject or send it back." },
      { heading: "Arabic, and what happens when scripture is recited",
        body: "Recited Quran is matched against a corpus of all 6,236 ayat and rendered as the ayah with its translation, set in Amiri, instead of as a phonetic guess from a transcriber. Arabic speech that is not scripture is captioned in Arabic with an English line beneath it, drawn from a second translation pass. Auto-detect switches per segment, so an English talk containing recitation is handled as both languages rather than one. Any clip containing scripture is flagged and forced into human review, and that flag never bypasses, including on accounts running automation." },
      { heading: "What it does not do yet",
        body: "The full clip editor sits behind a coming-soon notice and is not available yet, so clips are reviewed and published as rendered. There are no view counts, watch time or audience figures anywhere in the product, because no connected platform sends them to us and inventing them would be worse than leaving them out. There is no mobile app, and Studio multi-account posting is not built. Everything else described on this page is running today, and this page is kept honest about the difference." },
    ],
    faqs: [
      { q: "What is DeenClipped?",
        a: "DeenClipped turns long Islamic lectures into short vertical clips with captions burned in, then holds every clip in a review queue until a person approves it. You import from a YouTube URL or upload an MP4, choose the stretch to process, and get finished clips you can approve, reject, schedule and publish to accounts you have connected yourself." },
      { q: "Does DeenClipped post to social media automatically?",
        a: "No. Every clip lands in a review queue and waits for a decision first. Once approved it can be scheduled into posting windows, four a day or eight on Studio, and sent to YouTube, TikTok, Instagram and Facebook accounts you connect yourself. Each destination reports its own state, so one platform refusing a post does not mark the whole clip failed." },
      { q: "How does DeenClipped handle Quran recitation in a clip?",
        a: "Recitation is matched against all 6,236 ayat and captioned as the ayah with its translation in Amiri. The Quran Recitation template captions scripture and nothing else, so an aside or a half-heard word never appears under a verse. Any clip containing scripture is flagged and forced into human review, whatever your automation settings say." },
      { q: "Is DeenClipped free?",
        a: "Basic is free and includes 40 tokens over a seven-day trial. One token is one source minute, and you are charged for the stretch you select, not the length of the whole video. Re-rendering a clip, cutting more clips from the same lecture and editing never cost extra tokens, and failed renders or clips rejected before export are never charged. Pro and Studio are paid weekly, monthly or yearly." },
    ],
    ctaLabel: "Start Basic free",
  },

};
